security:
    # Configuration pour le hachage des mots de passe
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateur pour charger les utilisateurs de la base de données
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                # Uncomment the following line to redirect after logout
                # target: app_any_route

            remember_me:
                secret: 'bbcb7f4924dd97f7f72b72594c653a23'
                lifetime: 604800
                path: /
                # Uncomment to always enable the remember me feature
                # always_remember_me: true

            # Activation des différentes méthodes d'authentification
            # https://symfony.com/doc/current/security.html#the-firewall

            # Uncomment to enable user impersonation
            # switch_user: true

    # Contrôle d'accès pour certaines sections du site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Uncomment the following line to restrict access to profile route
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Configuration spécifique pour les tests qui réduit le coût des hashages
            # pour un gain de performance
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon