controllers:
    resource: '../src/Controller/'
    type: annotation  # Vous pouvez garder cette ligne pour les routes basées sur annotations

home:
    path: /
    controller: App\Controller\HomeController::index

blog:
    path: /blog
    controller: App\Controller\BlogController::index

admin:
    path: /admin
    controller: App\Controller\AdminController::index
    requirements:
        _role: ROLE_ADMIN

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

admin_messages:
    path: /admin/messages
    controller: App\Controller\MentionController::index

mentions_legales:
    path: /mentions-legales
    controller: App\Controller\MentionController::mentionsLegales

politique_confidentialite:
    path: /politique-confidentialite
    controller: App\Controller\MentionController::politiqueConfidentialite